spring:
  datasource:
    url: jdbc:mysql://localhost:3306/claim_request_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
      data-locations: classpath:/data.sql

  main:
    banner-mode: off