INSERT INTO question (question_content, type)
VALUES ('Tôi và người yêu bị thu hút nhau ngay từ lần đầu gặp mặt.', 'LOVE'),
       ('Tôi và người yêu có sự "hợp nhau" về mặt thể xác.', 'LOVE'),
       ('Chuyện quan hệ của chúng tôi rất mãnh liệt và thỏa mãn.', 'LOVE'),
       ('Tôi cảm thấy tôi và người yêu sinh ra là để dành cho nhau.', 'LOVE'),
       ('Tôi và người yêu nhanh chóng gắn bó về mặt cảm xúc.', 'LOVE'),
       ('Tôi và người yêu thực sự hiểu nhau.', 'LOVE'),
       ('Người yêu tôi phù hợp với hình mẫu lý tưởng về ngoại hình của tôi.', 'LOVE'),
       ('Tôi cố giữ cho người yêu không quá chắc chắn về mức độ cam kết của tôi.', 'LOVE'),
       ('Tôi tin rằng những điều người yêu không biết sẽ không làm tổn thương họ.', 'LOVE'),
       ('Đôi khi tôi phải giấu chuyện giữa hai người yêu để họ không phát hiện ra nhau.', 'LOVE'),
       ('Tôi có thể vượt qua một mối quan hệ tình cảm khá dễ dàng và nhanh chóng.', 'LOVE'),
       ('Người yêu tôi sẽ buồn nếu biết một vài điều tôi đã làm với người khác.', 'LOVE'),
       ('Khi người yêu tôi trở nên quá phụ thuộc, tôi muốn rút lui một chút.', 'LOVE'),
       ('Tôi thích chơi "trò chơi tình yêu" với nhiều người khác nhau.', 'LOVE'),
       ('Khó để nói chính xác đâu là ranh giới giữa tình bạn và tình yêu.', 'LOVE'),
       ('Tình yêu đích thực bắt đầu bằng sự quan tâm chân thành trong một thời gian.', 'LOVE'),
       ('Tôi mong sẽ luôn là bạn với người tôi yêu.', 'LOVE'),
       ('Kiểu tình yêu tốt nhất phát triển từ một tình bạn lâu dài.', 'LOVE'),
       ('Tình bạn của chúng tôi dần dần chuyển thành tình yêu theo thời gian.', 'LOVE'),
       ('Tình yêu thực sự là một tình bạn sâu sắc, không phải là cảm xúc huyền bí nào đó.', 'LOVE'),
       ('Những mối tình làm tôi thỏa mãn nhất đều phát triển từ tình bạn tốt.', 'LOVE'),
       ('Tôi cân nhắc một người sẽ trở thành người như thế nào trong tương lai trước khi gắn bó.', 'LOVE'),
       ('Tôi cố lên kế hoạch cho cuộc đời mình trước khi chọn người yêu.', 'LOVE'),
       ('Tốt nhất là yêu một người có hoàn cảnh tương đồng với mình.', 'LOVE'),
       ('Một yếu tố chính trong việc chọn người yêu là người đó có khiến gia đình tôi hài lòng hay không.', 'LOVE'),
       ('Một yếu tố quan trọng khi chọn bạn đời là liệu người đó có thể trở thành cha/mẹ tốt hay không.', 'LOVE'),
       ('Một yếu tố tôi cân nhắc khi chọn bạn đời là người đó ảnh hưởng thế nào đến sự nghiệp của tôi.', 'LOVE'),
       ('Trước khi gắn bó sâu sắc với ai, tôi cố đánh giá xem yếu tố di truyền của họ có hợp với tôi không – phòng khi có con sau này.',
        'LOVE'),
       ('Khi giữa tôi và người yêu có chuyện không ổn, tôi thấy đau bụng.', 'LOVE'),
       ('Khi mối quan hệ kết thúc, tôi buồn đến mức thậm chí từng nghĩ đến việc tự tử.', 'LOVE'),
       ('Đôi khi tôi phấn khích vì đang yêu đến mức không thể ngủ được.', 'LOVE'),
       ('Khi người yêu không quan tâm đến tôi, tôi thấy toàn thân mệt mỏi.', 'LOVE'),
       ('Khi đang yêu, tôi khó tập trung vào những việc khác.', 'LOVE'),
       ('Tôi không thể thư giãn nếu nghi ngờ người yêu đang ở cùng người khác.', 'LOVE'),
       ('Nếu người yêu phớt lờ tôi, đôi khi tôi làm những điều ngớ ngẩn để gây chú ý lại.', 'LOVE'),
       ('Tôi luôn cố giúp đỡ người yêu vượt qua những thời điểm khó khăn.', 'LOVE'),
       ('Tôi thà chịu khổ còn hơn để người yêu phải chịu khổ.', 'LOVE'),
       ('Tôi không thể hạnh phúc trừ khi tôi đặt hạnh phúc của người yêu lên trước.', 'LOVE'),
       ('Tôi thường sẵn lòng hy sinh mong muốn của mình để người yêu đạt được điều họ muốn.', 'LOVE'),
       ('Tài sản của tôi đều là của người yêu nếu họ muốn dùng.', 'LOVE'),
       ('Khi người yêu nổi giận với tôi, tôi vẫn yêu họ trọn vẹn và vô điều kiện.', 'LOVE'),
       ('Tôi sẵn sàng chịu đựng mọi thứ vì người yêu của mình.', 'LOVE'),
       ('Việc lên kế hoạch cho các hoạt động gia đình rất khó khăn vì chúng tôi hiểu lầm nhau.', 'FAMILY'),
       ('Chúng tôi giải quyết hầu hết các vấn đề hàng ngày trong nhà.', 'FAMILY'),
       ('Khi ai đó buồn bã, những người khác sẽ biết lý do.', 'FAMILY'),
       ('Khi bạn yêu cầu ai đó làm điều gì đó, bạn phải kiểm tra xem họ đã làm chưa.', 'FAMILY'),
       ('Nếu ai đó gặp rắc rối, những người khác sẽ can thiệp quá mức.', 'FAMILY'),
       ('Trong lúc khủng hoảng, chúng tôi có thể dựa vào nhau để được hỗ trợ.', 'FAMILY'),
       ('Chúng tôi không biết phải làm gì khi có trường hợp khẩn cấp xảy ra.', 'FAMILY'),
       ('Đôi khi chúng tôi hết những thứ cần thiết.', 'FAMILY'),
       ('Chúng tôi ngại thể hiện tình cảm với nhau.', 'FAMILY'),
       ('Chúng tôi đảm bảo các thành viên hoàn thành trách nhiệm gia đình của mình.', 'FAMILY'),
       ('Chúng tôi không thể nói chuyện với nhau về nỗi buồn mà mình cảm thấy.', 'FAMILY'),
       ('Chúng tôi thường hành động dựa trên các quyết định đã thống nhất để giải quyết vấn đề.', 'FAMILY'),
       ('Bạn chỉ thu hút được sự quan tâm của người khác khi điều gì đó quan trọng đối với họ.', 'FAMILY'),
       ('Bạn không thể biết người khác đang cảm thấy thế nào qua lời nói của họ.', 'FAMILY'),
       ('Công việc gia đình không được phân chia đều.', 'FAMILY'),
       ('Mỗi cá nhân đều được chấp nhận như chính con người họ.', 'FAMILY'),
       ('Bạn có thể dễ dàng phá vỡ các quy tắc.', 'FAMILY'),
       ('Mọi người nói thẳng thay vì nói bóng gió.', 'FAMILY'),
       ('Một số người trong chúng tôi không phản ứng về mặt cảm xúc.', 'FAMILY'),
       ('Chúng tôi biết phải làm gì trong trường hợp khẩn cấp.', 'FAMILY'),
       ('Chúng tôi tránh thảo luận về những lo sợ và mối quan tâm của mình.', 'FAMILY'),
       ('Thật khó để nói với nhau về những cảm xúc mềm yếu.', 'FAMILY'),
       ('Chúng tôi gặp khó khăn trong việc đáp ứng các nghĩa vụ tài chính.', 'FAMILY'),
       ('Sau khi gia đình cố gắng giải quyết một vấn đề, chúng tôi thường thảo luận xem nó có hiệu quả hay không.',
        'FAMILY'),
       ('Chúng tôi quá ích kỷ.', 'FAMILY'),
       ('Chúng tôi có thể bày tỏ cảm xúc với nhau.', 'FAMILY'),
       ('Chúng tôi không có quy định rõ ràng về thói quen vệ sinh.', 'FAMILY'),
       ('Chúng tôi không thể hiện tình yêu với nhau.', 'FAMILY'),
       ('Chúng tôi nói chuyện trực tiếp với nhau thay vì thông qua người trung gian.', 'FAMILY'),
       ('Mỗi người trong chúng tôi đều có nhiệm vụ và trách nhiệm riêng.', 'FAMILY'),
       ('Trong gia đình có nhiều cảm xúc tiêu cực.', 'FAMILY'),
       ('Chúng tôi có quy định về việc đánh người.', 'FAMILY'),
       ('Chúng tôi chỉ quan tâm đến nhau khi có điều gì đó khiến chúng tôi hứng thú.', 'FAMILY'),
       ('Có rất ít thời gian để theo đuổi sở thích cá nhân.', 'FAMILY'),
       ('Chúng tôi thường không nói đúng những gì mình nghĩ.', 'FAMILY'),
       ('Chúng tôi cảm thấy được chấp nhận như con người của mình.', 'FAMILY'),
       ('Chúng tôi chỉ quan tâm đến nhau khi có lợi cho bản thân.', 'FAMILY'),
       ('Chúng tôi giải quyết hầu hết những xung đột cảm xúc nảy sinh.', 'FAMILY'),
       ('Tình cảm bị xếp sau các vấn đề khác trong gia đình.', 'FAMILY'),
       ('Chúng tôi thảo luận xem ai chịu trách nhiệm làm việc nhà.', 'FAMILY'),
       ('Việc đưa ra quyết định là một vấn đề đối với gia đình chúng tôi.', 'FAMILY'),
       ('Gia đình chúng tôi chỉ quan tâm đến nhau khi có thể thu được lợi ích cá nhân.', 'FAMILY'),
       ('Chúng tôi thẳng thắn (nói trực tiếp, rõ ràng) với nhau.', 'FAMILY'),
       ('Chúng tôi không tuân theo bất kỳ quy tắc hoặc tiêu chuẩn nào.', 'FAMILY'),
       ('Nếu ai đó được yêu cầu làm việc gì đó, họ cần được nhắc nhở.', 'FAMILY'),
       ('Chúng tôi có khả năng đưa ra quyết định về cách giải quyết vấn đề.', 'FAMILY'),
       ('Nếu quy tắc bị phá vỡ, chúng tôi không biết điều gì sẽ xảy ra.', 'FAMILY'),
       ('Trong gia đình chúng tôi, mọi thứ đều có thể xảy ra (không có giới hạn rõ ràng).', 'FAMILY'),
       ('Chúng tôi thể hiện sự dịu dàng, âu yếm với nhau.', 'FAMILY'),
       ('Chúng tôi đối mặt trực tiếp với các vấn đề liên quan đến cảm xúc.', 'FAMILY'),
       ('Chúng tôi không hòa thuận với nhau.', 'FAMILY'),
       ('Chúng tôi không nói chuyện với nhau khi đang tức giận.', 'FAMILY'),
       ('Chúng tôi thường không hài lòng với các công việc gia đình được giao.', 'FAMILY'),
       ('Dù có ý tốt, chúng tôi lại can thiệp quá mức vào cuộc sống của nhau.', 'FAMILY'),
       ('Gia đình chúng tôi có quy tắc cho các tình huống nguy hiểm.', 'FAMILY'),
       ('Chúng tôi tin tưởng và giãi bày với nhau.', 'FAMILY'),
       ('Chúng tôi khóc một cách cởi mở.', 'FAMILY'),
       ('Chúng tôi không có phương tiện di chuyển hợp lý.', 'FAMILY'),
       ('Khi không hài lòng với việc ai đó đã làm, chúng tôi sẽ nói thẳng với họ.', 'FAMILY'),
       ('Chúng tôi cố gắng nghĩ ra những cách khác nhau để giải quyết vấn đề.', 'FAMILY'),
       ('Tôi và bạn thân dành tất cả thời gian rảnh để ở bên nhau.', 'FRIEND'),
       ('Tôi có thể cãi nhau với bạn thân của mình.', 'FRIEND'),
       ('Nếu tôi quên mang theo cơm trưa hoặc cần một ít tiền, bạn tôi sẽ cho tôi mượn.', 'FRIEND'),
       ('Nếu tôi gặp vấn đề ở trường hoặc ở nhà, tôi có thể tâm sự với bạn thân của mình.', 'FRIEND'),
       ('Nếu bạn tôi phải chuyển đi nơi khác, tôi sẽ nhớ bạn ấy lắm.', 'FRIEND'),
       ('Bạn tôi thường nghĩ ra những điều thú vị để chúng tôi cùng làm.', 'FRIEND'),
       ('Dù tôi đã nhắc nhở, bạn tôi vẫn có thể làm phiền hoặc chọc giận tôi.', 'FRIEND'),
       ('Bạn tôi giúp đỡ tôi khi tôi gặp khó khăn với việc gì đó.', 'FRIEND'),
       ('Nếu có điều gì làm tôi bận tâm, tôi có thể kể cho bạn nghe, kể cả khi đó là điều tôi không thể nói với người khác.',
        'FRIEND'),
       ('Tôi cảm thấy hạnh phúc khi ở bên bạn thân của mình.', 'FRIEND'),
       ('Tôi và bạn thường đến nhà nhau sau giờ học hoặc vào cuối tuần.', 'FRIEND'),
       ('Tôi và bạn thân có thể cãi nhau nhiều lần.', 'FRIEND'),
       ('Bạn tôi sẽ giúp tôi nếu tôi cần.', 'FRIEND'),
       ('Nếu tôi xin lỗi sau một cuộc cãi nhau, bạn tôi vẫn sẽ giận tôi.', 'FRIEND'),
       ('Tôi vẫn nghĩ đến bạn mình ngay cả khi bạn không có ở đó.', 'FRIEND'),
       ('Đôi khi tôi và bạn chỉ ngồi trò chuyện về trường lớp, thể thao, hay những điều mình thích.', 'FRIEND'),
       ('Tôi và bạn không đồng ý với nhau về nhiều điều.', 'FRIEND'),
       ('Nếu có bạn khác làm phiền tôi, bạn thân tôi sẽ giúp tôi.', 'FRIEND'),
       ('Nếu tôi hoặc bạn tôi làm điều gì đó khiến người kia không vui, chúng tôi có thể làm hòa dễ dàng.', 'FRIEND'),
       ('Khi tôi làm tốt điều gì đó, bạn tôi cảm thấy vui cho tôi.', 'FRIEND'),
       ('Bạn tôi sẽ đứng về phía tôi nếu có bạn khác gây rắc rối.', 'FRIEND'),
       ('Nếu tôi và bạn có cãi nhau, chỉ cần nói “xin lỗi” là mọi chuyện sẽ ổn.', 'FRIEND'),
       ('Đôi khi bạn tôi làm điều gì đó cho tôi hoặc khiến tôi cảm thấy mình đặc biệt.', 'FRIEND'),
       ('Tôi cảm thấy áp lực vì phải hoàn thành tất cả bài tập đúng hạn.', 'STUDY'),
       ('Tôi thường xuyên lo lắng về kết quả học tập của mình.', 'STUDY'),
       ('Tôi cảm thấy khó khăn khi phải đối mặt với yêu cầu học tập quá cao.', 'STUDY'),
       ('Tôi cảm thấy căng thẳng khi không hoàn thành các bài tập đúng thời gian.', 'STUDY'),
       ('Tôi lo lắng về kỳ thi sắp tới.', 'STUDY'),
       ('Tôi cảm thấy không đủ thời gian để học bài.', 'STUDY'),
       ('Tôi cảm thấy mệt mỏi khi phải học quá nhiều môn.', 'STUDY'),
       ('Tôi cảm thấy căng thẳng vì kỳ vọng quá cao từ gia đình về kết quả học tập của tôi.', 'STUDY'),
       ('Tôi cảm thấy áp lực vì phải duy trì điểm số cao.', 'STUDY'),
       ('Tôi thấy lo lắng về việc không thể hiểu hết bài học trên lớp.', 'STUDY'),
       ('Tôi cảm thấy khó khăn khi phải đối mặt với giáo viên yêu cầu quá khắt khe.', 'STUDY'),
       ('Tôi cảm thấy không đủ tự tin khi làm bài kiểm tra.', 'STUDY'),
       ('Tôi lo lắng về việc mình không thể theo kịp tiến độ học tập.', 'STUDY'),
       ('Tôi cảm thấy căng thẳng vì không biết làm thế nào để chuẩn bị cho kỳ thi.', 'STUDY'),
       ('Tôi cảm thấy không thoải mái khi phải học trong môi trường học tập căng thẳng.', 'STUDY'),
       ('Tôi cảm thấy thất vọng với kết quả học tập của mình.', 'STUDY'),
       ('Tôi cảm thấy buồn khi không ai phản hồi bài viết của tôi trên mạng xã hội.', 'SOCIAL'),
       ('Tôi mong đợi sự chú ý mỗi khi đăng bài.', 'SOCIAL'),
       ('Việc không nhận được nhiều “like” khiến tôi cảm thấy không được công nhận.', 'SOCIAL'),
       ('Tôi thường xuyên kiểm tra phản hồi trên mạng xã hội.', 'SOCIAL'),
       ('Tôi cảm thấy cần phải chia sẻ mọi thứ trên mạng xã hội để cảm thấy quan trọng.', 'SOCIAL'),
       ('Những gì tôi thấy trên mạng xã hội khiến tôi cảm thấy mình không đủ tốt.', 'SOCIAL'),
       ('Tôi thường so sánh bản thân với người khác trên mạng xã hội.', 'SOCIAL'),
       ('Tôi cảm thấy mình không có giá trị khi nhìn thấy cuộc sống của người khác trên mạng xã hội.', 'SOCIAL'),
       ('Mạng xã hội khiến tôi cảm thấy mình thất bại.', 'SOCIAL'),
       ('Tôi cảm thấy muốn rút lui hoặc tự làm hại bản thân sau khi dùng mạng xã hội.', 'SOCIAL'),
       ('Tôi thích ở trên mạng xã hội hơn là đối mặt với thực tế.', 'SOCIAL'),
       ('Tôi dùng mạng xã hội để quên đi các vấn đề trong cuộc sống.', 'SOCIAL'),
       ('Trò chuyện qua mạng khiến tôi cảm thấy an toàn hơn ngoài đời.', 'SOCIAL'),
       ('Tôi cảm thấy thoải mái hơn khi thể hiện bản thân trên mạng.', 'SOCIAL'),
       ('Khi buồn chán hoặc lo lắng, tôi lập tức mở mạng xã hội.', 'SOCIAL');

INSERT INTO account (username, fullname, password)
VALUES ('user1@gmail.com', 'Nguyễn Văn A', '1000000001'),
       ('user2@gmail.com', 'Trần Thị B', '1000000002'),
       ('user3@gmail.com', 'Lê Văn C', '1000000003'),
       ('user4@gmail.com', 'Phạm Thị D', '1000000004'),
       ('user5@gmail.com', 'Hoàng Văn E', '1000000005'),
       ('user6@gmail.com', 'Đặng Thị F', '1000000006'),
       ('user7@gmail.com', 'Bùi Văn G', '1000000007'),
       ('user8@gmail.com', 'Ngô Thị H', '1000000008'),
       ('user9@gmail.com', 'Vũ Văn I', '1000000009'),
       ('user10@gmail.com', 'Đỗ Thị K', '1000000010');

INSERT INTO answer (answer_content, answer_point, answer_type)
VALUES ('Hoàn toàn không đồng ý', 1, 'STUDY'),
       ('Không đồng ý', 2, 'STUDY'),
       ('Không chắc chắn', 3, 'STUDY'),
       ('Đồng ý', 4, 'STUDY'),
       ('Hoàn toàn đồng ý', 5, 'STUDY'), --STUDY
       ('Rất không đồng ý', 1, 'SOCIAL'),
       ('Không đồng ý', 2, 'SOCIAL'),
       ('Trung lập', 3, 'SOCIAL'),
       ('Đồng ý', 4, 'SOCIAL'),
       ('Rất đồng ý', 5, 'SOCIAL'),       --SOCIAL
       ('Rất đồng ý', 1, 'LOVE'),
       ('Đồng ý vừa phải', 2, 'LOVE'),
       ('Trung lập', 3, 'LOVE'),
       ('Không đồng ý vừa phải', 4, 'LOVE'),
       ('Rất không đồng ý', 5, 'LOVE'),   --LOVE
       ('Hoàn toàn không đúng', 1, 'FRIEND'),
       ('Hơi đúng', 2, 'FRIEND'),
       ('Khá đúng', 3, 'FRIEND'),
       ('Rất đúng', 4, 'FRIEND'),
       ('Thật sự đúng', 5, 'FRIEND'),     --FRIEND
       ('Rất đồng ý', 1, 'FAMILY'),
       ('Đồng ý', 2, 'FAMILY'),
       ('Không đồng ý', 3, 'FAMILY'),
       ('Rất không đồng ý', 4, 'FAMILY'); --FAMILY